package routes

import (
	"github.com/gin-gonic/gin"
	"go.uber.org/zap"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	"github.com/RedShawn258/FinTrack/backend/internal/handlers"
	"github.com/RedShawn258/FinTrack/backend/internal/middlewares"
	_ "github.com/RedShawn258/FinTrack/backend/internal/docs" // docs is generated by Swag CLI
)

func SetupRoutes(router *gin.Engine, logger *zap.Logger, jwtSecret string) {
	// Note: Logger and JWT secret are already set in main.go middleware
	// No need to set them again here

	// Swagger documentation endpoint
	router.GET("/docs/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Public endpoints for authentication
	auth := router.Group("/api/v1/auth")
	{
		auth.POST("/register", handlers.RegisterHandler)
		auth.POST("/login", handlers.LoginHandler)
		auth.POST("/refresh", handlers.RefreshTokenHandler)
		auth.POST("/forgot-password", handlers.ForgotPasswordHandler)
		auth.POST("/reset-password", handlers.ResetPasswordHandler)
	}

	// Protected endpoints (JWT required)
	protected := router.Group("/api/v1")
	protected.Use(middlewares.AuthMiddleware())
	{
		// Profile endpoints
		protected.GET("/profile", handlers.GetProfileHandler)
		protected.PUT("/profile", handlers.UpdateProfileHandler)
		protected.POST("/profile/image", handlers.ProfileImageUploadHandler)

		// Budget endpoints
		protected.POST("/budgets", handlers.CreateBudget)
		protected.GET("/budgets", handlers.GetBudgets)
		protected.PUT("/budgets/:id", handlers.UpdateBudget)
		protected.DELETE("/budgets/:id", handlers.DeleteBudget)

		// Category endpoints
		protected.GET("/categories", handlers.GetCategories)
		protected.DELETE("/categories/:id", handlers.DeleteCategory)

		// Admin-only endpoints
		admin := protected.Group("")
		admin.Use(middlewares.RequireRole("admin"))
		{
			// Category management (admin only)
			admin.POST("/categories", handlers.CreateCategory)

			// User management (admin only)
			// admin.GET("/users", handlers.GetUsers) // TODO: implement GetUsers handler
		}

		// Transaction endpoints
		protected.POST("/transactions", handlers.CreateTransaction)
		protected.GET("/transactions", handlers.GetTransactions)
		protected.PUT("/transactions/:id", handlers.UpdateTransaction)
		protected.DELETE("/transactions/:id", handlers.DeleteTransaction)

		// Future feature endpoints (stub implementations)
		protected.GET("/features/gamification", handlers.GamificationHandler)
		protected.GET("/features/analytics", handlers.AnalyticsHandler)
		protected.GET("/features/notifications", handlers.NotificationHandler)

		// Forecasting feature
		protected.POST("/forecast/expenses", handlers.ForecastExpensesHandler)
	}
}
